[package]
name = "calc"
version = "1.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"], optional = true }


[features]
default = ["cli"]
cli = ["dep:clap"]


[[bin]]
name = "cli"
src = "./src/cli.rs"
required-features = ["cli"]

